#+TITLE: About

Your humble author likes the beach. And it's nice! But now? Drive to first stop sign and turn left. Obviously, I'd be the last person to forget that she said that awesome day.

MCY, March 2016/2017:
#+BEGIN_QUOTE
You can't out-train a bad essay.
#+END_QUOTE


Barbra W. Tuchman's /A Distant Mirror: The Calamitous 14th Century/:
#+BEGIN_QUOTE
Together the frescoes marked the start of a pervasive presence of Death in art, not yet the cult it was to become by the end of the century, but its beginning. ␤ Usually Death was personified as a skeleton with hourglass and scythe, in a white shroud or bare-bonred, grinning at the irony of man's fate reflected in his image: that all men, from beggar to emperor, from harlot to queen, from ragged clerk to Pope, must come to this. No matter what their poverty or power in life, all is vanity, equalized by death. The temporal is nothing; what matters is the after-life of the soul.
#+END_QUOTE



* The methods are too severe! Arr

+Twpnot be avoided+ 

Twp *can* be avoided. So long as we stick together and everyone squared away is. Fla-fal. Zeldri Epseechi is doing a fantastic job in her neck of the woods. Tough and smart, she loves our lights and will always be there with right thing. She has my CTE.



* What's more

LOVE IS GOTN. /Please note, none of the remarks here are mine./
